FROM nginx
COPY nginx.conf /etc/nginx/nginx.conf

ENV environment development
ENV app_name orders
ENV version "1.0.0"


LABEL app_name=$app_name
LABEL environment=$environment
LABEL version=$version

